services:
  - type: web
    name: rag-bot-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
      - key: SIMILARITY_THRESHOLD
        value: "0.9"
